### ISSUE TITLE
Reviews services never start for BookInfo demo

### ISSUE THREAD

**Issue by thrawn01** [istio/istio.github.io#1018]
Version: istio-0.5.1
OS: High Serria 10.13.3
```bash
$ kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml)
service "details" created
deployment "details-v1" created
service "ratings" created
deployment "ratings-v1" created
service "reviews" created
deployment "reviews-v1" created
deployment "reviews-v2" created
deployment "reviews-v3" created
service "productpage" created
deployment "productpage-v1" created
ingress "gateway" created

$ kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
details-v1-c9c6fd7b5-blkrj        2/2       Running   0          53s
productpage-v1-57c7c76897-8qph8   2/2       Running   0          53s
ratings-v1-5dc5dd6ccc-cm8mm       2/2       Running   0          53s
reviews-v1-7d9895b47c-r8bjt       1/2       Error     3          53s
reviews-v2-85c6cf8f97-ld5t8       1/2       Error     3          53s
reviews-v3-586dbcb589-5bkkz       1/2       Error     3          53s

$ kubectl logs reviews-v1-7d9895b47c-r8bjt reviews
Launching defaultServer (WebSphere Application Server 17.0.0.4/wlp-1.0.19.201712061531) on IBM J9 VM, version 8.0.5.7 - pxa6480sr5fp7-20171216_01(SR5 FP7) (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/17.0.0.4/lafiles/en.html
CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.NoClassDefFoundError: org.eclipse.osgi.internal.framework.EquinoxContainer
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.RuntimeException: java.lang.NoClassDefFoundError: org.eclipse.osgi.internal.framework.EquinoxContainer
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:524)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:211)
	at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:244)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:119)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.lang.NoClassDefFoundError: org.eclipse.osgi.internal.framework.EquinoxContainer
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
	at org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:24)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.startFramework(FrameworkManager.java:557)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchFramework(FrameworkManager.java:260)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:205)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.osgi.internal.framework.EquinoxContainer
	at com.ibm.ws.kernel.internal.classloader.JarFileClassLoader.findClass(JarFileClassLoader.java:121)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at com.ibm.ws.kernel.internal.classloader.BootstrapChildFirstJarClassloader.loadClass(BootstrapChildFirstJarClassloader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 11 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
	at com.ibm.ws.kernel.internal.classloader.JarFileClassLoader.getBytes(JarFileClassLoader.java:288)
	at com.ibm.ws.kernel.internal.classloader.JarResourceEntry.getBytes(JarResourceEntry.java:59)
	at com.ibm.ws.kernel.internal.classloader.JarFileClassLoader.findClass(JarFileClassLoader.java:117)
	... 15 more
```

**Comment by thrawn01** [comment]
Removed all images from docker and reset K8 and the containers started properly. 
```
$ docker rmi $(docker images -q)
```

**Comment by ldemailly** [comment]
strange but thanks

ps: next time please file issues like that in https://github.com/istio/issues/issues/new
