### ISSUE TITLE
Running Locally Fails

### ISSUE THREAD

**Issue by danehans** [istio/istio.github.io#763]
I am following the REAMDE and running the website locally fails:
```
> git clone https://github.com/istio/istio.github.io.git
Cloning into 'istio.github.io'...
remote: Counting objects: 7469, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 7469 (delta 14), reused 54 (delta 8), pack-reused 7395
Receiving objects: 100% (7469/7469), 18.55 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (4830/4830), done.

> cd istio.github.io/

> docker run --name istio-jekyll --volume=$(pwd):/srv/jekyll  -it -p 127.0.0.1:4000:4000 jekyll/jekyll:3.5.2 sh -c "bundle install && rake test && jekyll serve"
Unable to find image 'jekyll/jekyll:3.5.2' locally
3.5.2: Pulling from jekyll/jekyll
88286f41530e: Pull complete 
646f42db9346: Pull complete 
85e6f1a7a21f: Pull complete 
b6573fe11cb6: Pull complete 
acbba1ba745a: Pull complete 
cd801d87f781: Pull complete 
Digest: sha256:2b5d86838dc624858e742aab271fd75b8d7604c0872c02c8d57c1ef0d4c0d287
Status: Downloaded newer image for jekyll/jekyll:3.5.2
Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.0). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching rake 12.3.0
Installing rake 12.3.0
Using concurrent-ruby 1.0.5
Fetching minitest 5.10.3
Installing minitest 5.10.3
Using thread_safe 0.3.6
Fetching public_suffix 2.0.5
Installing public_suffix 2.0.5
Using bundler 1.15.4
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using colorator 1.1.0
Using colorize 0.8.1
Using ffi 1.9.18
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.0
Fetching net-dns 0.8.0
Installing net-dns 0.8.0
Using rb-fsevent 0.10.2
Fetching kramdown 1.14.0
Installing kramdown 1.14.0
Using liquid 4.0.0
Using mercenary 0.3.6
Fetching rouge 2.2.1
Installing rouge 2.2.1
Using safe_yaml 1.0.4
Using mini_portile2 2.3.0
Using jekyll-paginate 1.1.0
Fetching jekyll-swiss 0.4.0
Installing jekyll-swiss 0.4.0
Fetching unicode-display_width 1.3.0
Installing unicode-display_width 1.3.0
Using parallel 1.12.0
Using yell 2.0.7
Fetching i18n 0.9.1
Installing i18n 0.9.1
Fetching tzinfo 1.2.4
Installing tzinfo 1.2.4
Using addressable 2.5.2
Using coffee-script 2.4.1
Fetching ethon 0.11.0
Installing ethon 0.11.0
Using rb-inotify 0.9.10
Fetching faraday 0.13.1
Installing faraday 0.13.1
Fetching pathutil 0.16.0
Installing pathutil 0.16.0
Using nokogiri 1.8.1
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Using activesupport 4.2.9
Using jekyll-coffeescript 1.0.2
Using typhoeus 0.8.0
Using sass-listen 4.0.0
Fetching listen 3.0.6
Installing listen 3.0.6
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Using html-pipeline 2.7.1
Fetching html-proofer 3.7.4
Installing html-proofer 3.7.4
Fetching sass 3.5.3
Installing sass 3.5.3
Using jekyll-watch 1.5.0
Fetching octokit 4.7.0
Installing octokit 4.7.0
Using jekyll-sass-converter 1.5.0
Fetching github-pages-health-check 1.3.5
Installing github-pages-health-check 1.3.5
Fetching jekyll-gist 1.4.1
Installing jekyll-gist 1.4.1
Fetching jekyll 3.6.2
Installing jekyll 3.6.2
Fetching jekyll-avatar 0.5.0
Installing jekyll-avatar 0.5.0
Fetching jekyll-default-layout 0.1.4
Installing jekyll-default-layout 0.1.4
Using jekyll-feed 0.9.2
Fetching jekyll-github-metadata 2.9.3
Installing jekyll-github-metadata 2.9.3
Using jekyll-mentions 1.2.0
Fetching jekyll-optional-front-matter 0.2.0
Installing jekyll-optional-front-matter 0.2.0
Fetching jekyll-readme-index 0.1.0
Installing jekyll-readme-index 0.1.0
Using jekyll-redirect-from 0.12.1
Fetching jekyll-relative-links 0.5.1
Installing jekyll-relative-links 0.5.1
Fetching jekyll-seo-tag 2.3.0
Installing jekyll-seo-tag 2.3.0
Using jekyll-sitemap 1.1.1
Fetching jekyll-titles-from-headings 0.4.0
Installing jekyll-titles-from-headings 0.4.0
Using jemoji 0.8.1
Using minima 2.1.1
Fetching jekyll-include-cache 0.1.0
Installing jekyll-include-cache 0.1.0
Fetching jekyll-theme-architect 0.1.0
Installing jekyll-theme-architect 0.1.0
Fetching jekyll-theme-cayman 0.1.0
Installing jekyll-theme-cayman 0.1.0
Fetching jekyll-theme-dinky 0.1.0
Installing jekyll-theme-dinky 0.1.0
Fetching jekyll-theme-hacker 0.1.0
Installing jekyll-theme-hacker 0.1.0
Fetching jekyll-theme-leap-day 0.1.0
Installing jekyll-theme-leap-day 0.1.0
Fetching jekyll-theme-merlot 0.1.0
Installing jekyll-theme-merlot 0.1.0
Fetching jekyll-theme-midnight 0.1.0
Installing jekyll-theme-midnight 0.1.0
Fetching jekyll-theme-minimal 0.1.0
Installing jekyll-theme-minimal 0.1.0
Fetching jekyll-theme-modernist 0.1.0
Installing jekyll-theme-modernist 0.1.0
Fetching jekyll-theme-primer 0.5.2
Installing jekyll-theme-primer 0.5.2
Fetching jekyll-theme-slate 0.1.0
Installing jekyll-theme-slate 0.1.0
Fetching jekyll-theme-tactile 0.1.0
Installing jekyll-theme-tactile 0.1.0
Fetching jekyll-theme-time-machine 0.1.0
Installing jekyll-theme-time-machine 0.1.0
Fetching github-pages 169
Installing github-pages 169
Bundle complete! 5 Gemfile dependencies, 81 gems now installed.
Bundled gems are installed into /usr/local/bundle.
bundle exec jekyll build
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 14.026 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["LinkCheck", "ScriptCheck", "HtmlCheck", "ImageCheck"] on ["./_site"] on *.html... 


Found 0 links in the cache...
Adding 225 links to the cache...
Removing 0 links from the cache...
Checking 225 external links...
Ran on 140 files!


- ./_site/blog/istio-service-mesh-for-microservices.html
  *  External link http://github.com/istio/issues/issues failed: got a time out (response code 0)
- ./_site/docs/concepts/policy-and-control/mixer-config.html
  *  External link https://newrelic.com failed: got a time out (response code 0)
- ./_site/docs/setup/eureka/quick-start.html
  *  External link http://gliderlabs.github.io/registrator/latest failed: got a time out (response code 0)
- ./_site/docs/tasks/telemetry/using-istio-dashboard.html
  *  External link http://docs.grafana.org failed: got a time out (response code 0)
- ./_site/troubleshooting/index.html
  *  External link https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css failed: got a time out (response code 0)
  *  External link https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js failed: got a time out (response code 0)
rake aborted!
HTML-Proofer found 6 failures!
/usr/local/bundle/gems/html-proofer-3.7.4/lib/html-proofer/runner.rb:167:in `print_failed_tests'
/usr/local/bundle/gems/html-proofer-3.7.4/lib/html-proofer/runner.rb:48:in `run'
/srv/jekyll/rakefile:8:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by ldemailly** [comment]
check your network / in your docker settings maybe ? and try again, as it's caching it may work subsequent times

this being said I'm working on some flakiness observed with 301s in circleci

**Comment by ldemailly** [comment]
try updating to head, I changed the htmlproofer / typhoeus and it may work better for you now ?

**Comment by danehans** [comment]
@ldemailly that did the trick. Thanks for your help.

**Comment by ldemailly** [comment]
glad to hear! thank you!
